%%
%% Autogenerated by Thrift Compiler (1.0.0-dev)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(multiplexing_Calculator_thrift).
-behaviour(thrift_service).


-include("multiplexing_Calculator_thrift.hrl").

-export([struct_info/1, function_info/2]).

struct_info('i am a dummy struct') -> undefined.
%%% interface
% add(This, X, Y)
function_info('add', params_type) ->
  {struct, [{1, i32},
          {2, i32}]}
;
function_info('add', reply_type) ->
  i32;
function_info('add', exceptions) ->
  {struct, []}
;
function_info(_Func, _Info) -> no_function.

